#!/bin/bash

## exec_waiter

set -euo pipefail

JOB_NAME="qa-test-runner"
REGION="us-west1"
PROJECT="automated-qa-runner"

echo "Starting Cloud Run Job: $JOB_NAME"

gcloud run jobs execute "$JOB_NAME" \
  --region "$REGION" \
  --project "$PROJECT" \
  --format="json" \
  --task-timeout="2m" \
  --wait