name: QA Auto Runner

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  qa:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: "actions/checkout@v4"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: "automated-qa-runner"
          workload_identity_provider: ${{ secrets.WI_PROVIDER }}
          service_account: "cicd-github@automated-qa-runner.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      # artifact registry currently exists with an image so we will skip for now

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Terraform
        env:
          TF_VAR_project_id: "automated-qa-runner"
          TF_VAR_slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          cd terraform/step-2-app
          terraform init -input=false
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      - name: Run Cloud Run Job
        run: |
          cd scripts
          chmod +x exec_waiter
          ./exec_waiter

      - name: Terraform Destroy QA Infra
        if: always()
        env:
          TF_VAR_project_id: "automated-qa-runner"
          TF_VAR_slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          cd terraform/step-2-app
          terraform init -input=false
          terraform destroy -auto-approve
